Add notification for any step

diff --git a/.github/workflows/generate-token-lists.yml b/.github/workflows/generate-token-lists.yml
--- a/.github/workflows/generate-token-lists.yml
+++ b/.github/workflows/generate-token-lists.yml
@@ -69,7 +69,7 @@ jobs:
           path: ./src/ArbTokenLists/arbed_arb_whitelist_era.json
           key: ${{ github.sha }}
 
-  generate-token-list:
+  generate-token-lists:
     name: 'Generate'
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
@@ -134,8 +134,12 @@ jobs:
         id: run_command
         if: success() || failure() # Always would allow manually canceled workflow to run
         run: |
-          echo "commands=${{matrix.commands.name}}" >> $GITHUB_OUTPUT
-          ${{ matrix.commands.command }}
+          if ${{ matrix.commands.name }} ; then
+            exit 1
+          else
+            echo ${{ matrix.commands.name }} >> $GITHUB_OUTPUT
+            exit 0
+          fi
 
       - name: Deploy (Test folder)
         if: ${{ github.event_name == 'pull_request' }}
@@ -145,32 +149,38 @@ jobs:
         if: ${{ github.event_name != 'pull_request' }}
         run: 'aws s3 sync ./src/ s3://${{ secrets.AWS_BUCKET }} --exclude "*" --include "FullList/*.json" --include "ArbTokenLists/*.json" --acl "public-read"'
 
-      # - name: Post errors to Slack channel
-      #   if: failure()
-      #   uses: slackapi/slack-github-action@v1.23.0
-      #   with:
-      #     channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
-      #     payload: |
-      #       {
-      #         "blocks": [
-      #           {
-      #             "type": "section",
-      #             "text": {
-      #               "type": "mrkdwn",
-      #               "text": "Token list generation failed (${{ matrix.commands.name }})"
-      #             }
-      #           },
-      #           {
-      #             "type": "divider"
-      #           },
-      #           {
-      #             "type": "section",
-      #             "text": {
-      #               "type": "mrkdwn",
-      #               "text": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
-      #             }
-      #           }
-      #         ]
-      #       }
-      #   env:
-      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+  error-alerts:
+    runs-on: ubuntu-latest
+    needs: [install, fetchWhitelist, generate-token-lists]
+    # Run this job if any of the job in needs array failed
+    if: ${{ always() && contains(needs.*.result, 'failure') }}
+    steps:
+      - name: Post errors to Slack channel
+        uses: slackapi/slack-github-action@v1.23.0
+        with:
+          # channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
+          channel-id: C04QLBVM3HQ
+          payload: |
+            {
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "Token list generation failed (${{ needs.generate-token-lists.outputs }})"
+                  }
+                },
+                {
+                  "type": "divider"
+                },
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
